name: supermarket
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.0
  persistent_bottom_nav_bar: ^5.0.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/constants/
  filename: assets.dart
  field_prefix: null
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
